spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
    bus:
      enabled: true
      trace:
        enabled: true
  profiles:
    active: native
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
