server:
  port: 8083

spring:
  application:
    name: user

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.109:8081/eureka