server:
  port: 8082

spring:
  application:
    name: web

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.109:8081/eureka

feign:
  hystrix:
    #feign客户端调用服务，可以使用feign内置的Hystrix功能
    enabled: true