server:
  port: 8083

spring:
  application:
    name: user

management:
  endpoints:
    web:
      exposure:
        include: /actuator/hystrix.stream

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka