server:
  port: 8082

spring:
  application:
    name: web

management:
  endpoints:
    web:
      exposure:
        include: /actuator/hystrix.stream

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka

feign:
  hystrix:
    #feign客户端调用服务，可以使用feign内置的Hystrix功能
    enabled: true

